### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Jbarget**

### CODE REVIEW

**Comment by nelsonic** [comment]
this PR only "fails" because of https://github.com/dwyl/goodparts/issues/274 which is fixex in my PR: #276 😉

**Comment by Jbarget** [comment]
fab fab, no worries :)

**Comment by nelsonic** [comment]
@Jbarget I wasn't suggesting we _close_ your PR... 😢 
I was actually suggesting you grab the code from: 
`rules/es6.js` and `test/fixtures/es6.js` in `this` commit:
https://github.com/dwyl/goodparts/pull/273/files#diff-f92ae6e935255e90991a27ce10091994
so your PR will pass and we can _merge_ it...! 👍 

> Please re-open it so we can get that typo fixed asap as I have _no idea_ when my PR will be ready... thanks! ❤️

**Comment by nelsonic** [comment]
@Jbarget thanks for fixing that typo and adding the `'no-return-await': 'off'` rule. 👍

**Comment by Jbarget** [comment]
whoops sorry, my process has been lacking:

fixes https://github.com/dwyl/goodparts/issues/274

**Comment by nelsonic** [comment]
@Jbarget it's fine. 👍

**Pull request merged**
