### PR TITLE
Sams issues + Extra Config

### LINKED ISSUE #15: no-cond-assign
http://eslint.org/docs/rules/no-cond-assign

In conditional statements, it is very easy to mistype a comparison operator (such as ==) as an assignment operator (such as =)
Therefore,

```
no-cond-assign: [2, "never"]
```

see also http://stackoverflow.com/questions/2576571/assign-variable-in-if-condition-statement-good-practice-or-not

### LINKED ISSUE #18: no-constant-condition
http://eslint.org/docs/rules/no-constant-condition

incorrect code:
```
if (false) {
    doSomethingUnfinished();
}
```

This will avoid typos and unnecessary code

```
no-constant-condition: [2, "never"]
```

### LINKED ISSUE #21: no-control-regex
http://eslint.org/docs/rules/no-control-regex

We may want to use this, so for now:

```
no-control-regex: 2
```

see the list of these characters: http://www.ascii-code.com/

### LINKED ISSUE #22: no-dupe-args
http://eslint.org/docs/rules/no-dupe-args

There should be no duplicate arguments in functions,

```
no-dupe-args: [2, "never"]
```

### LINKED ISSUE #25: no-duplicate-case
http://eslint.org/docs/rules/no-duplicate-case

There should be no duplicate cases in switch statements,

```
no-duplicate-case: [2, "never"]
```

### LINKED ISSUE #28: no-empty
http://eslint.org/docs/rules/no-empty

There should be no empty if, while, switch, try statements

```
no-empty: [2, "never"]
```

### LINKED ISSUE #30: no-extra-boolean-cast
http://eslint.org/docs/rules/no-extra-boolean-cast

The results of these expressions will be coerced to boolean in if statements

no-extra-boolean-cast: "error"

### LINKED ISSUE #35: no-func-assign
http://eslint.org/docs/rules/no-func-assign

We shouldn't be reassigning functions

no-func-assign: [2, "never"]

### LINKED ISSUE #45: no-irregular-whitespace
http://eslint.org/docs/rules/no-irregular-whitespace

For formatting reasons and potential issues in modern browsers

```
no-irregular-whitespace: [2, {"skipStrings": true, "skipComments": true, "skipRegExps": true, "skipTemplates": true]
```

A little unsure for the four skipping options

Other linting configs for this config option:
[standard](https://github.com/feross/eslint-config-standard/blob/master/eslintrc.json#L76)
[airbnb](https://github.com/1hella/eslint-config-airbnb-es5/blob/master/.eslintrc#L48)

### LINKED ISSUE #56: valid-jsdoc
http://eslint.org/docs/rules/valid-jsdoc

Prefer:

returns over return,
param over params, arg or args

```
valid-jsdoc: [2, ["prefer": { "arg": "param", "argument": "param", "return": "returns" }]
```

### LINKED ISSUE #59: accessor-pairs
http://eslint.org/docs/rules/accessor-pairs

Constructing a setter without a getter is a mistake

```
accessor-pairs: 2
```

### LINKED ISSUE #61: blocked-scoped-var
http://eslint.org/docs/rules/block-scoped-var

This rule aims to reduce the usage of variables outside of their binding context

```
blocked-scoped-var: 2
```

e.g.
incorrect
```
function doIf() {
    if (true) {
        var build = true;
    }

    console.log(build);
}
```

correct
```
function doIf() {
    var build;

    if (true) {
        build = true;
    }

    console.log(build);
}
```

### LINKED ISSUE #63: complexity
http://eslint.org/docs/rules/complexity

Reduces the use of overly complex functions

```
"complexity": ["error", 10]
```

This is what I feel is a good complexity level, I'm open for changing it though

### LINKED ISSUE #65: curly
http://eslint.org/docs/rules/curly

I think for consistency we should always require curly brackets for if and while statements

### LINKED ISSUE #68: dot-location
http://eslint.org/docs/rules/dot-location

Consistency of where the dot is placed will increase code readability

```
dot-location: [2, "property"]
```

### LINKED ISSUE #71: eqeqeq
http://eslint.org/docs/rules/eqeqeq

Preference `!==` and `===` to `!=` and `==`

### LINKED ISSUE #72: no-alert
http://eslint.org/docs/rules/no-alert

I agree with "JavaScripts’ alert, confirm, and prompt functions are widely considered to be obtrusive as UI elements", we should not be using this in production

```
no-alert: 2
```

### LINKED ISSUE #74: no-case-declarations
http://eslint.org/docs/rules/no-case-declarations

It seems that wrapping your clauses in blocks retains the scope of where it was defined and not throughout the switch statement which can be quite useful

But it makes writing switch statements a little uglier.

I think though the better config option is:

```
no-case-declarations: 2
```

e.g.
incorrect:
```
switch (foo) {
    case 1:
        let x = 1;
        break;
    case 2:
        const y = 2;
        break;
    case 3:
        function f() {}
        break;
    default:
        class C {}
}
```

correct:
```
switch (foo) {
    case 1: {
        let x = 1;
        break;
    }
    case 2: {
        const y = 2;
        break;
    }
    case 3: {
        function f() {}
        break;
    }
    default: {
        class C {}
    }
}
```

### LINKED ISSUE #87: no-else-return
http://eslint.org/docs/rules/no-else-return

If there is a return inside of an if statement the else becomes unnessary

```
no-else-return: 2
```

incorrect
```
function foo() {
    if (x) {
        return y;
    } else {
        return z;
    }
}
```

correct

```
function foo() {
    if (x) {
        return y;
    return z;
}
```

### LINKED ISSUE #88: no-empty-pattern
http://eslint.org/docs/rules/no-empty-pattern

NA since we are not using object destructuring

### LINKED ISSUE #89: no-eval
http://eslint.org/docs/rules/no-eval

We havn't been using this, but just in case, since "JavaScript’s eval() function is potentially dangerous and is often misused"

```
no-eval: 2
```

### LINKED ISSUE #90: no-extra-bind
http://eslint.org/docs/rules/no-extra-bind

"The bind() method is used to create functions with specific this values"

If not referencing the this keyword inside of your function, then bind is useless

```
no-extra-bind: 2
```

### LINKED ISSUE #95: no-fallthrough
http://eslint.org/docs/rules/no-fallthrough

```
no-fallthrough: 2
```

Forgetting to write break in each case is an easy mistake to make and fallthrough isn't generally considered good practice so allowing it may lead to readability issues

### LINKED ISSUE #97: no-global-assign
http://eslint.org/docs/rules/no-global-assign

This rule disallows modifications to read-only global variables.

```
"no-global-assign": 2
```

If we need globals, we should have them in exceptions as follows, if any needed come up we should include them here, currently though there aren't any
```
"no-global-assign": ["error", {"exceptions": ["Object"]}]
```

### LINKED ISSUE #110: no-implicit-globals
http://eslint.org/docs/rules/no-implicit-globals

```
no-implicit-globals: [2, parserOptions": { "sourceType": "module" }]
```

### LINKED ISSUE #115: no-invalid-this
http://eslint.org/docs/rules/no-invalid-this

```
no-invalid-this: 2
```

I can't think of a reason to do this other than inside of function constructors

### LINKED ISSUE #120: no-labels
http://eslint.org/docs/rules/no-labels

```
no-labels: 2
```

These look pretty horrible https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/label, we probably shouldn't use them

### LINKED ISSUE #125: no-loop-func
http://eslint.org/docs/rules/no-loop-func

If you are unsure why shouldn't write functions within a loop google it (or read this: http://stackoverflow.com/questions/750486/javascript-closure-inside-loops-simple-practical-example)

```
no-loop-func: 2
```

### LINKED ISSUE #130: no-multi-spaces
http://eslint.org/docs/rules/no-multi-spaces

My preference would be to have this turned on and to disallow multi spaces

```
no-multi-spaces: 2
```

But, I know some people like to line up their variables like so:

```
var longvariablename = 'foo',
            othervar = 'bar';
```

So open for discussion

### LINKED ISSUE #131: no-new-func
http://eslint.org/docs/rules/no-new-func

```
no-new-func: 2
```

Nobody writes like this any more, disallow

### LINKED ISSUE #133: no-new
http://eslint.org/docs/rules/no-new

```
no-new: 2
```

Whenever you create a new object constructor you should assign it as follows:

correct
```
var thing = new Thing();

Thing();
```

incorrect
```
new Thing();
```

### LINKED ISSUE #137: no-octal
http://eslint.org/docs/rules/no-octal

Numbers with preceeding 0s in javascript can lead to inconsistencies,

you should reference octal numbers as strings

```
no-octal: 2
```

### LINKED ISSUE #142: no-proto
http://eslint.org/docs/rules/no-proto

"`__proto__` property has been deprecated as of ECMAScript 3.1 and shouldn’t be used in the code. Use `getPrototypeOf` method instead."

```
no-proto: 2
```

### LINKED ISSUE #147: no-return-assign
http://eslint.org/docs/rules/no-return-assign

You should not be returning an assignment

This is incorrect:
```
function doSomething() {
    return foo = bar + 2;
}
```

config:
```
no-return-assign: "always"
```

### LINKED ISSUE #159: no-self-assign
http://eslint.org/docs/rules/no-self-assign

Assigning a variable to itself is pointless

e.g.
```
foo = foo;
```
is pointless

Also assigning an object property to itself is pointless
```
obj.prop = obj.prop
```

Therefore:
```
no-self-assign: [2, {props: true}]
```

### LINKED ISSUE #163: no-sequences
http://eslint.org/docs/rules/no-sequences

This is some of the worst syntax I've seen:
```
var a = (3, 5); // a = 5
```

The comma operator includes multiple expressions where only one is expected

```
no-sequences: 2
```

### LINKED ISSUE #166: no-unused-labels
http://eslint.org/docs/rules/no-unused-labels

```
no-unused-labels: "error"
```

### LINKED ISSUE #172: no-useless-concat
http://eslint.org/docs/rules/no-useless-concat

e.g. this is a useless concat:
```
var foo = "a" + "b";
```
Instead use:
```
var foo = "ab";
```

```
no-useless-concat: 2
```

### LINKED ISSUE #178: no-unmodified-loop-condition
http://eslint.org/docs/rules/no-unmodified-loop-condition

If not modifying the condition, it is probably a mistake and may not end

incorrect
```
while (node) {
    doSomething(node);
}
```

correct
```
while (node) {
    doSomething(node);
    node = node.parent;
}
```

```
no-unmodified-loop-condition
```

### LINKED ISSUE #179: no-void
http://eslint.org/docs/rules/no-void

Void operator was useful prior to es5, it is used to always return undefined

```
no-void: 2
```

### LINKED ISSUE #181: no-with
http://eslint.org/docs/rules/no-with

"Use of the with statement is not recommended, as it may be the source of confusing bugs and compatibility issues" from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/with)

We shouldn't be using `with` syntax, so

```
no-with: 2
```

### LINKED ISSUE #182: vars-on-top
http://eslint.org/docs/rules/vars-on-top

It is best to define your variables at the top of your function declaration or top of program

```
vars-on-top: 2
```

### LINKED ISSUE #183: yoda
http://eslint.org/docs/rules/yoda

This rule ensures that the variable is checked against the literal value and not the other way around:

correct
```
if (color === "red") {
    // ...
}
```

incorrect
```
if ("red" === color) {
    // ...
}
```

Also `exceptRange: true` allows:
```
if (x < -1 || 1 < x) {
    // ...
}
```
So,

```
yoda: [2, "never", { "exceptRange": true }]
```

### PR DESCRIPTION
**Pull request by eliascodes**
Adds config rules for following sections:
* best practises
* possible errors

Also:
* Added `parserOptions` and `env` options to the eslint config. If we want the config to be `npm i`-and-go then we probably need them.
* Fixed linter errors in the test runner index.

All tested.

Fixes #183
Fixes #182 
Fixes #181 
Fixes #179 
Fixes #178 
Fixes #172 
Fixes #166 
Fixes #163 
Fixes #159 
Fixes #147 
Fixes #142 
Fixes #137 
Fixes #133 
Fixes #131 
Fixes #130 
Fixes #125 
Fixes #120 
Fixes #115 
Fixes #110 
Fixes #97 
Fixes #95 
Fixes #90 
Fixes #89 
Fixes #88 
Fixes #87 
Fixes #74 
Fixes #72 
Fixes #71 
Fixes #68 
Fixes #65 
Fixes #63 
Fixes #61 
Fixes #59 
Fixes #56 
Fixes #45 
Fixes #35 
Fixes #30 
Fixes #28 
Fixes #25 
Fixes #22 
Fixes #21 
Fixes #18 
Fixes #15

### CODE REVIEW

**Comment by jrans** [comment]
@eliascodes

**Comment by eliascodes** [comment]
@jrans conflicts fixed

**Comment by shouston3** [comment]
You've missed a couple of links to issues in `best_practices.js` and `possible_errors.js`

**Comment by nelsonic** [comment]
@eliascodes please fix merge conflict then re-assign. thanks!

**Comment by jrans** [comment]
:+1:

**Comment by nelsonic** [comment]
Sweet! 🍭 
❤️ ✅ 🎉

**Pull request merged**
